# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c26595e5ef29aa1fae84bb5c493765fd6c7312ee62348c2f1bd973515bef7d71bf7dc968ce1671e029cb53c17ecf08b72a7dbdad041ec045b36a69fcfe0f38a0
  auth0_client_id: <%= ENV["IKA4fXnqskym1uDfxs_CbMCGFNz_X1fm"] %>
  auth0_client_secret: <%= ENV["Uer7a7XDDlA2ShfpKVG1GeGg7B04x_7xvvGH0W4NHAyj0ODi7BoVANCDX30OfJ4N"] %>

test:
  secret_key_base: 8fc6eda81385af1938612f45f90138c8b8ea659171e3d6914f8140f1ec615ebc27b6b73cd15df4e12e8907b7b8adbe2e5f90515c16271f1152b9f684f71d0289
  auth0_client_id: <%= ENV["IKA4fXnqskym1uDfxs_CbMCGFNz_X1fm"] %>
  auth0_client_secret: <%= ENV["Uer7a7XDDlA2ShfpKVG1GeGg7B04x_7xvvGH0W4NHAyj0ODi7BoVANCDX30OfJ4N"] %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["IKA4fXnqskym1uDfxs_CbMCGFNz_X1fm"] %>
  auth0_client_secret: <%= ENV["Uer7a7XDDlA2ShfpKVG1GeGg7B04x_7xvvGH0W4NHAyj0ODi7BoVANCDX30OfJ4N"] %>
